// <auto-generated />
using System;
using ConsultancyApp.Data.EfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultancyApp.Data.Migrations
{
    [DbContext(typeof(ConsultancyAppContex))]
    partial class ConsultancyAppContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "90699b40-fa10-4920-9b87-03be756306e2"
                        },
                        new
                        {
                            Id = 2,
                            UserId = "022169b4-75b1-4c4c-a27e-0e6660a656b9"
                        },
                        new
                        {
                            Id = 3,
                            UserId = "f053af86-2a08-44b5-bb35-6516478773ba"
                        },
                        new
                        {
                            Id = 4,
                            UserId = "7d97d1e4-fce7-445e-9752-91816ceb8c2a"
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("PsychologistId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryDescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDescriptionId")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryDescriptionId = 0,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7448),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7519),
                            Name = "Bireysel Terapi",
                            Url = "bireysel-terapi"
                        },
                        new
                        {
                            Id = 2,
                            CategoryDescriptionId = 0,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7523),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7524),
                            Name = "İlişki Terapisi",
                            Url = "iliski-terapisi"
                        },
                        new
                        {
                            Id = 3,
                            CategoryDescriptionId = 0,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7525),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7526),
                            Name = "Aile Terapisi",
                            Url = "aile-terapisi"
                        },
                        new
                        {
                            Id = 4,
                            CategoryDescriptionId = 0,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7528),
                            IsApproved = false,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7528),
                            Name = "Çocuk Terapisi",
                            Url = "cocuk-terapisi"
                        },
                        new
                        {
                            Id = 5,
                            CategoryDescriptionId = 0,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7530),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7530),
                            Name = "Ergen Terapisi",
                            Url = "ergen-terapisi"
                        },
                        new
                        {
                            Id = 6,
                            CategoryDescriptionId = 0,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7532),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7532),
                            Name = "Oyun Terapisi",
                            Url = "oyun-terapisi"
                        },
                        new
                        {
                            Id = 7,
                            CategoryDescriptionId = 0,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7534),
                            IsApproved = false,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7534),
                            Name = "Sanat Danışmanlık",
                            Url = "sanat-danismanlik"
                        },
                        new
                        {
                            Id = 8,
                            CategoryDescriptionId = 0,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7536),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 293, DateTimeKind.Local).AddTicks(7536),
                            Name = "Cinsel Yönetimi",
                            Url = "cinsel-terapi"
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.CategoryDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForWho")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("How")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("HowLong")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PositiveEffect")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("What")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoryDescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ForWho = "Depreston, Kaygı,Öfke,Bağımlılık,Aile Sorunları,Düşük benlik kaygısı gibi sorunları yaşayan insanlara yardımcı olabilir.",
                            How = "Bilişsel davranışçı terapi (CBT) en yaygın ve etkili terapi türlerinden biridir. Bu yaklaşım, insanların düşünceler, duygular ve davranışlar arasındaki bağlantıya bakmasına yardımcı olur. Bu süreçte insanlar olumsuz düşünme kalıplarını pozitif olanlarla değiştirebilirler. Bilişsel Davranışçı Terapi'nin arkasındaki inanç, sağlıklı düşüncelerin genellikle olumlu duyguları ve üretken eylemleri teşvik ettiği yönündedir.",
                            HowLong = "rapinin süresi ve sıklığı, danışanların ihtiyaçlarına ve hedeflerindeki ilerlemesine bağlı olarak, tek oturum ile birkaç yıla kadar süren bir aralıkta değişkenlik gösterebilir.",
                            PositiveEffect = "Online terapi, endişe ve depresyondan ilişki sorunlarına ve işle ilgili strese kadar her türlü sorunu tedavi etmek için kullanılabilir. Online terapinin geleneksel yüz yüze terapiden daha fazla olmasa da aynı derecede faydalı olduğu kanıtlanmıştır. Bazı çalışmalar insanların online terapiden daha fazla memnun olduklarını gösteriyor. Dolayısıyla, online terapi, geleneksel tedavinin yalnızca aynı faydalarını sağlamakla kalmaz, aynı zamanda daha fazla kolaylık ve esneklik sunar.",
                            Purpose = "Genel olarak, psikoterapinin amacı kişilerin mental kaygıları hakkında konuşmak ve danışanların daha üretken, psikolojik olarak daha sağlıklı yaşamlar sürmelerine ve ilerlemelerine yardımcı olmaktır.",
                            What = "Bireysel terapi, danışanların duygularını, inançlarını veya davranışlarını araştırmak için eğitimli bir terapistle (güvenli, şefkatli ve gizli bir ortamda) birebir çalıştıkları bir süreçtir. Terapinin genel amaçları değişime ilham vermek veya yaşam kalitesini artırmak olabilir. İnsanlar, tek başına yüzleşmeleri zor olan konularda yardım almak için terapi isteyebilir. Bireysel terapi ayrıca terapi, psikoterapi, psikososyal terapi, konuşma terapisi ve danışmanlık olarak da adlandırılabilir. En yaygın terapi şekli olan bireysel terapi, psikanaliz ve bilişsel-davranışçı terapi gibi birçok farklı terapi stilini kapsayabilir."
                        },
                        new
                        {
                            Id = 2,
                            ForWho = "Depreston, Kaygı,Öfke,Bağımlılık,Aile Sorunları,Düşük benlik kaygısı gibi sorunları yaşayan insanlara yardımcı olabilir.",
                            How = "Bilişsel davranışçı terapi (CBT) en yaygın ve etkili terapi türlerinden biridir. Bu yaklaşım, insanların düşünceler, duygular ve davranışlar arasındaki bağlantıya bakmasına yardımcı olur. Bu süreçte insanlar olumsuz düşünme kalıplarını pozitif olanlarla değiştirebilirler. Bilişsel Davranışçı Terapi'nin arkasındaki inanç, sağlıklı düşüncelerin genellikle olumlu duyguları ve üretken eylemleri teşvik ettiği yönündedir.",
                            HowLong = "rapinin süresi ve sıklığı, danışanların ihtiyaçlarına ve hedeflerindeki ilerlemesine bağlı olarak, tek oturum ile birkaç yıla kadar süren bir aralıkta değişkenlik gösterebilir.",
                            PositiveEffect = "Online terapi, endişe ve depresyondan ilişki sorunlarına ve işle ilgili strese kadar her türlü sorunu tedavi etmek için kullanılabilir. Online terapinin geleneksel yüz yüze terapiden daha fazla olmasa da aynı derecede faydalı olduğu kanıtlanmıştır. Bazı çalışmalar insanların online terapiden daha fazla memnun olduklarını gösteriyor. Dolayısıyla, online terapi, geleneksel tedavinin yalnızca aynı faydalarını sağlamakla kalmaz, aynı zamanda daha fazla kolaylık ve esneklik sunar.",
                            Purpose = "Genel olarak, psikoterapinin amacı kişilerin mental kaygıları hakkında konuşmak ve danışanların daha üretken, psikolojik olarak daha sağlıklı yaşamlar sürmelerine ve ilerlemelerine yardımcı olmaktır.",
                            What = "İlişki terapi, danışanların duygularını, inançlarını veya davranışlarını araştırmak için eğitimli bir terapistle (güvenli, şefkatli ve gizli bir ortamda) birebir çalıştıkları bir süreçtir. Terapinin genel amaçları değişime ilham vermek veya yaşam kalitesini artırmak olabilir. İnsanlar, tek başına yüzleşmeleri zor olan konularda yardım almak için terapi isteyebilir. Bireysel terapi ayrıca terapi, psikoterapi, psikososyal terapi, konuşma terapisi ve danışmanlık olarak da adlandırılabilir. En yaygın terapi şekli olan bireysel terapi, psikanaliz ve bilişsel-davranışçı terapi gibi birçok farklı terapi stilini kapsayabilir."
                        },
                        new
                        {
                            Id = 3,
                            ForWho = "Depreston, Kaygı,Öfke,Bağımlılık,Aile Sorunları,Düşük benlik kaygısı gibi sorunları yaşayan insanlara yardımcı olabilir.",
                            How = "Bilişsel davranışçı terapi (CBT) en yaygın ve etkili terapi türlerinden biridir. Bu yaklaşım, insanların düşünceler, duygular ve davranışlar arasındaki bağlantıya bakmasına yardımcı olur. Bu süreçte insanlar olumsuz düşünme kalıplarını pozitif olanlarla değiştirebilirler. Bilişsel Davranışçı Terapi'nin arkasındaki inanç, sağlıklı düşüncelerin genellikle olumlu duyguları ve üretken eylemleri teşvik ettiği yönündedir.",
                            HowLong = "rapinin süresi ve sıklığı, danışanların ihtiyaçlarına ve hedeflerindeki ilerlemesine bağlı olarak, tek oturum ile birkaç yıla kadar süren bir aralıkta değişkenlik gösterebilir.",
                            PositiveEffect = "Online terapi, endişe ve depresyondan ilişki sorunlarına ve işle ilgili strese kadar her türlü sorunu tedavi etmek için kullanılabilir. Online terapinin geleneksel yüz yüze terapiden daha fazla olmasa da aynı derecede faydalı olduğu kanıtlanmıştır. Bazı çalışmalar insanların online terapiden daha fazla memnun olduklarını gösteriyor. Dolayısıyla, online terapi, geleneksel tedavinin yalnızca aynı faydalarını sağlamakla kalmaz, aynı zamanda daha fazla kolaylık ve esneklik sunar.",
                            Purpose = "Genel olarak, psikoterapinin amacı kişilerin mental kaygıları hakkında konuşmak ve danışanların daha üretken, psikolojik olarak daha sağlıklı yaşamlar sürmelerine ve ilerlemelerine yardımcı olmaktır.",
                            What = "Aile terapi, danışanların duygularını, inançlarını veya davranışlarını araştırmak için eğitimli bir terapistle (güvenli, şefkatli ve gizli bir ortamda) birebir çalıştıkları bir süreçtir. Terapinin genel amaçları değişime ilham vermek veya yaşam kalitesini artırmak olabilir. İnsanlar, tek başına yüzleşmeleri zor olan konularda yardım almak için terapi isteyebilir. Bireysel terapi ayrıca terapi, psikoterapi, psikososyal terapi, konuşma terapisi ve danışmanlık olarak da adlandırılabilir. En yaygın terapi şekli olan bireysel terapi, psikanaliz ve bilişsel-davranışçı terapi gibi birçok farklı terapi stilini kapsayabilir."
                        },
                        new
                        {
                            Id = 4,
                            ForWho = "Depreston, Kaygı,Öfke,Bağımlılık,Aile Sorunları,Düşük benlik kaygısı gibi sorunları yaşayan insanlara yardımcı olabilir.",
                            How = "Bilişsel davranışçı terapi (CBT) en yaygın ve etkili terapi türlerinden biridir. Bu yaklaşım, insanların düşünceler, duygular ve davranışlar arasındaki bağlantıya bakmasına yardımcı olur. Bu süreçte insanlar olumsuz düşünme kalıplarını pozitif olanlarla değiştirebilirler. Bilişsel Davranışçı Terapi'nin arkasındaki inanç, sağlıklı düşüncelerin genellikle olumlu duyguları ve üretken eylemleri teşvik ettiği yönündedir.",
                            HowLong = "rapinin süresi ve sıklığı, danışanların ihtiyaçlarına ve hedeflerindeki ilerlemesine bağlı olarak, tek oturum ile birkaç yıla kadar süren bir aralıkta değişkenlik gösterebilir.",
                            PositiveEffect = "Online terapi, endişe ve depresyondan ilişki sorunlarına ve işle ilgili strese kadar her türlü sorunu tedavi etmek için kullanılabilir. Online terapinin geleneksel yüz yüze terapiden daha fazla olmasa da aynı derecede faydalı olduğu kanıtlanmıştır. Bazı çalışmalar insanların online terapiden daha fazla memnun olduklarını gösteriyor. Dolayısıyla, online terapi, geleneksel tedavinin yalnızca aynı faydalarını sağlamakla kalmaz, aynı zamanda daha fazla kolaylık ve esneklik sunar.",
                            Purpose = "Genel olarak, psikoterapinin amacı kişilerin mental kaygıları hakkında konuşmak ve danışanların daha üretken, psikolojik olarak daha sağlıklı yaşamlar sürmelerine ve ilerlemelerine yardımcı olmaktır.",
                            What = "ÇOcuk terapi, danışanların duygularını, inançlarını veya davranışlarını araştırmak için eğitimli bir terapistle (güvenli, şefkatli ve gizli bir ortamda) birebir çalıştıkları bir süreçtir. Terapinin genel amaçları değişime ilham vermek veya yaşam kalitesini artırmak olabilir. İnsanlar, tek başına yüzleşmeleri zor olan konularda yardım almak için terapi isteyebilir. Bireysel terapi ayrıca terapi, psikoterapi, psikososyal terapi, konuşma terapisi ve danışmanlık olarak da adlandırılabilir. En yaygın terapi şekli olan bireysel terapi, psikanaliz ve bilişsel-davranışçı terapi gibi birçok farklı terapi stilini kapsayabilir."
                        },
                        new
                        {
                            Id = 5,
                            ForWho = "Depreston, Kaygı,Öfke,Bağımlılık,Aile Sorunları,Düşük benlik kaygısı gibi sorunları yaşayan insanlara yardımcı olabilir.",
                            How = "Bilişsel davranışçı terapi (CBT) en yaygın ve etkili terapi türlerinden biridir. Bu yaklaşım, insanların düşünceler, duygular ve davranışlar arasındaki bağlantıya bakmasına yardımcı olur. Bu süreçte insanlar olumsuz düşünme kalıplarını pozitif olanlarla değiştirebilirler. Bilişsel Davranışçı Terapi'nin arkasındaki inanç, sağlıklı düşüncelerin genellikle olumlu duyguları ve üretken eylemleri teşvik ettiği yönündedir.",
                            HowLong = "rapinin süresi ve sıklığı, danışanların ihtiyaçlarına ve hedeflerindeki ilerlemesine bağlı olarak, tek oturum ile birkaç yıla kadar süren bir aralıkta değişkenlik gösterebilir.",
                            PositiveEffect = "Online terapi, endişe ve depresyondan ilişki sorunlarına ve işle ilgili strese kadar her türlü sorunu tedavi etmek için kullanılabilir. Online terapinin geleneksel yüz yüze terapiden daha fazla olmasa da aynı derecede faydalı olduğu kanıtlanmıştır. Bazı çalışmalar insanların online terapiden daha fazla memnun olduklarını gösteriyor. Dolayısıyla, online terapi, geleneksel tedavinin yalnızca aynı faydalarını sağlamakla kalmaz, aynı zamanda daha fazla kolaylık ve esneklik sunar.",
                            Purpose = "Genel olarak, psikoterapinin amacı kişilerin mental kaygıları hakkında konuşmak ve danışanların daha üretken, psikolojik olarak daha sağlıklı yaşamlar sürmelerine ve ilerlemelerine yardımcı olmaktır.",
                            What = "Ergen terapi, danışanların duygularını, inançlarını veya davranışlarını araştırmak için eğitimli bir terapistle (güvenli, şefkatli ve gizli bir ortamda) birebir çalıştıkları bir süreçtir. Terapinin genel amaçları değişime ilham vermek veya yaşam kalitesini artırmak olabilir. İnsanlar, tek başına yüzleşmeleri zor olan konularda yardım almak için terapi isteyebilir. Bireysel terapi ayrıca terapi, psikoterapi, psikososyal terapi, konuşma terapisi ve danışmanlık olarak da adlandırılabilir. En yaygın terapi şekli olan bireysel terapi, psikanaliz ve bilişsel-davranışçı terapi gibi birçok farklı terapi stilini kapsayabilir."
                        },
                        new
                        {
                            Id = 6,
                            ForWho = "Depreston, Kaygı,Öfke,Bağımlılık,Aile Sorunları,Düşük benlik kaygısı gibi sorunları yaşayan insanlara yardımcı olabilir.",
                            How = "Bilişsel davranışçı terapi (CBT) en yaygın ve etkili terapi türlerinden biridir. Bu yaklaşım, insanların düşünceler, duygular ve davranışlar arasındaki bağlantıya bakmasına yardımcı olur. Bu süreçte insanlar olumsuz düşünme kalıplarını pozitif olanlarla değiştirebilirler. Bilişsel Davranışçı Terapi'nin arkasındaki inanç, sağlıklı düşüncelerin genellikle olumlu duyguları ve üretken eylemleri teşvik ettiği yönündedir.",
                            HowLong = "rapinin süresi ve sıklığı, danışanların ihtiyaçlarına ve hedeflerindeki ilerlemesine bağlı olarak, tek oturum ile birkaç yıla kadar süren bir aralıkta değişkenlik gösterebilir.",
                            PositiveEffect = "Online terapi, endişe ve depresyondan ilişki sorunlarına ve işle ilgili strese kadar her türlü sorunu tedavi etmek için kullanılabilir. Online terapinin geleneksel yüz yüze terapiden daha fazla olmasa da aynı derecede faydalı olduğu kanıtlanmıştır. Bazı çalışmalar insanların online terapiden daha fazla memnun olduklarını gösteriyor. Dolayısıyla, online terapi, geleneksel tedavinin yalnızca aynı faydalarını sağlamakla kalmaz, aynı zamanda daha fazla kolaylık ve esneklik sunar.",
                            Purpose = "Genel olarak, psikoterapinin amacı kişilerin mental kaygıları hakkında konuşmak ve danışanların daha üretken, psikolojik olarak daha sağlıklı yaşamlar sürmelerine ve ilerlemelerine yardımcı olmaktır.",
                            What = "Oyun terapi, danışanların duygularını, inançlarını veya davranışlarını araştırmak için eğitimli bir terapistle (güvenli, şefkatli ve gizli bir ortamda) birebir çalıştıkları bir süreçtir. Terapinin genel amaçları değişime ilham vermek veya yaşam kalitesini artırmak olabilir. İnsanlar, tek başına yüzleşmeleri zor olan konularda yardım almak için terapi isteyebilir. Bireysel terapi ayrıca terapi, psikoterapi, psikososyal terapi, konuşma terapisi ve danışmanlık olarak da adlandırılabilir. En yaygın terapi şekli olan bireysel terapi, psikanaliz ve bilişsel-davranışçı terapi gibi birçok farklı terapi stilini kapsayabilir."
                        },
                        new
                        {
                            Id = 7,
                            ForWho = "Depreston, Kaygı,Öfke,Bağımlılık,Aile Sorunları,Düşük benlik kaygısı gibi sorunları yaşayan insanlara yardımcı olabilir.",
                            How = "Bilişsel davranışçı terapi (CBT) en yaygın ve etkili terapi türlerinden biridir. Bu yaklaşım, insanların düşünceler, duygular ve davranışlar arasındaki bağlantıya bakmasına yardımcı olur. Bu süreçte insanlar olumsuz düşünme kalıplarını pozitif olanlarla değiştirebilirler. Bilişsel Davranışçı Terapi'nin arkasındaki inanç, sağlıklı düşüncelerin genellikle olumlu duyguları ve üretken eylemleri teşvik ettiği yönündedir.",
                            HowLong = "rapinin süresi ve sıklığı, danışanların ihtiyaçlarına ve hedeflerindeki ilerlemesine bağlı olarak, tek oturum ile birkaç yıla kadar süren bir aralıkta değişkenlik gösterebilir.",
                            PositiveEffect = "Online terapi, endişe ve depresyondan ilişki sorunlarına ve işle ilgili strese kadar her türlü sorunu tedavi etmek için kullanılabilir. Online terapinin geleneksel yüz yüze terapiden daha fazla olmasa da aynı derecede faydalı olduğu kanıtlanmıştır. Bazı çalışmalar insanların online terapiden daha fazla memnun olduklarını gösteriyor. Dolayısıyla, online terapi, geleneksel tedavinin yalnızca aynı faydalarını sağlamakla kalmaz, aynı zamanda daha fazla kolaylık ve esneklik sunar.",
                            Purpose = "Genel olarak, psikoterapinin amacı kişilerin mental kaygıları hakkında konuşmak ve danışanların daha üretken, psikolojik olarak daha sağlıklı yaşamlar sürmelerine ve ilerlemelerine yardımcı olmaktır.",
                            What = "Sanat terapi, danışanların duygularını, inançlarını veya davranışlarını araştırmak için eğitimli bir terapistle (güvenli, şefkatli ve gizli bir ortamda) birebir çalıştıkları bir süreçtir. Terapinin genel amaçları değişime ilham vermek veya yaşam kalitesini artırmak olabilir. İnsanlar, tek başına yüzleşmeleri zor olan konularda yardım almak için terapi isteyebilir. Bireysel terapi ayrıca terapi, psikoterapi, psikososyal terapi, konuşma terapisi ve danışmanlık olarak da adlandırılabilir. En yaygın terapi şekli olan bireysel terapi, psikanaliz ve bilişsel-davranışçı terapi gibi birçok farklı terapi stilini kapsayabilir."
                        },
                        new
                        {
                            Id = 8,
                            ForWho = "Depreston, Kaygı,Öfke,Bağımlılık,Aile Sorunları,Düşük benlik kaygısı gibi sorunları yaşayan insanlara yardımcı olabilir.",
                            How = "Bilişsel davranışçı terapi (CBT) en yaygın ve etkili terapi türlerinden biridir. Bu yaklaşım, insanların düşünceler, duygular ve davranışlar arasındaki bağlantıya bakmasına yardımcı olur. Bu süreçte insanlar olumsuz düşünme kalıplarını pozitif olanlarla değiştirebilirler. Bilişsel Davranışçı Terapi'nin arkasındaki inanç, sağlıklı düşüncelerin genellikle olumlu duyguları ve üretken eylemleri teşvik ettiği yönündedir.",
                            HowLong = "rapinin süresi ve sıklığı, danışanların ihtiyaçlarına ve hedeflerindeki ilerlemesine bağlı olarak, tek oturum ile birkaç yıla kadar süren bir aralıkta değişkenlik gösterebilir.",
                            PositiveEffect = "Online terapi, endişe ve depresyondan ilişki sorunlarına ve işle ilgili strese kadar her türlü sorunu tedavi etmek için kullanılabilir. Online terapinin geleneksel yüz yüze terapiden daha fazla olmasa da aynı derecede faydalı olduğu kanıtlanmıştır. Bazı çalışmalar insanların online terapiden daha fazla memnun olduklarını gösteriyor. Dolayısıyla, online terapi, geleneksel tedavinin yalnızca aynı faydalarını sağlamakla kalmaz, aynı zamanda daha fazla kolaylık ve esneklik sunar.",
                            Purpose = "Genel olarak, psikoterapinin amacı kişilerin mental kaygıları hakkında konuşmak ve danışanların daha üretken, psikolojik olarak daha sağlıklı yaşamlar sürmelerine ve ilerlemelerine yardımcı olmaktır.",
                            What = "Cinsel terapi, danışanların duygularını, inançlarını veya davranışlarını araştırmak için eğitimli bir terapistle (güvenli, şefkatli ve gizli bir ortamda) birebir çalıştıkları bir süreçtir. Terapinin genel amaçları değişime ilham vermek veya yaşam kalitesini artırmak olabilir. İnsanlar, tek başına yüzleşmeleri zor olan konularda yardım almak için terapi isteyebilir. Bireysel terapi ayrıca terapi, psikoterapi, psikososyal terapi, konuşma terapisi ve danışmanlık olarak da adlandırılabilir. En yaygın terapi şekli olan bireysel terapi, psikanaliz ve bilişsel-davranışçı terapi gibi birçok farklı terapi stilini kapsayabilir."
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("userId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2d75e05d-f650-453c-a1fb-305396ede74f",
                            Description = "Yöneticiler",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "f69957c7-6805-4d84-aa1c-a4f7956eb8e4",
                            Description = "Kullanıcılar",
                            Name = "Customer",
                            NormalizedName = "Customer"
                        },
                        new
                        {
                            Id = "2b7b70ec-d6cf-42bc-bfd8-336a35616140",
                            Description = "Psikologlar",
                            Name = "Psychologist",
                            NormalizedName = "PSYCHOLOGIST"
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "90699b40-fa10-4920-9b87-03be756306e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b3dc27e-3107-47a1-9c2f-c7817f66e729",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "selvi@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Selvi",
                            LastName = "Kartal",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedEmail = "SELVI@GMAIL.COM",
                            NormalizedName = "SELVIKARTAL",
                            NormalizedUserName = "SELVI",
                            PasswordHash = "AQAAAAIAAYagAAAAEAODhRy0JaxsTiKS2J5rrjFE2ivBFcfmB8rW5rUKOHQqgekcwB1J4J4fqVDpHo+Svg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2cdc16a6-c9e5-450b-87f2-ffd369923549",
                            TwoFactorEnabled = false,
                            Type = 1,
                            UserName = "selvi"
                        },
                        new
                        {
                            Id = "022169b4-75b1-4c4c-a27e-0e6660a656b9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b017a109-5aa1-4497-8c87-f4880b9d8478",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Emma",
                            LastName = "Deniz",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedEmail = "EMMA@GMAIL.COM",
                            NormalizedName = "EMMADENIZ",
                            NormalizedUserName = "EMMA",
                            PasswordHash = "AQAAAAIAAYagAAAAEM4JeWtEsENFuQlWK2cuZkB01Y4TbNsfKCuC1yUV2Z7hnstcSFyn3ZWvkA6sr9d2OQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d88285b1-fcaa-4113-8551-b1ecadf3d7dd",
                            TwoFactorEnabled = false,
                            Type = 1,
                            UserName = "emma"
                        },
                        new
                        {
                            Id = "f053af86-2a08-44b5-bb35-6516478773ba",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fc73c33e-cb07-4b85-951f-945561088aaf",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sema@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Sema",
                            LastName = "Yıldırım",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedEmail = "SEMA@GMAIL.COM",
                            NormalizedName = "SEMAYILDIRIM",
                            NormalizedUserName = "SEMA",
                            PasswordHash = "AQAAAAIAAYagAAAAEPFDWCgU7bHG3IS7XFxdFOlhR5ECA5/4Su8t06NHRVaOf6LBufUNXUAc3oxin65LgA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "492d920f-ff27-4f23-8103-cf9e21e25fc6",
                            TwoFactorEnabled = false,
                            Type = 0,
                            UserName = "sema"
                        },
                        new
                        {
                            Id = "7d97d1e4-fce7-445e-9752-91816ceb8c2a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0869929-523b-4778-9f84-ff0ecdf73b4d",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "selin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Selin",
                            LastName = "Kara",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedEmail = "SELIN@GMAIL.COM",
                            NormalizedName = "SELINKARA",
                            NormalizedUserName = "SELIN",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "228f22f4-63f8-4b45-b57a-97625e8a86ae",
                            TwoFactorEnabled = false,
                            Type = 2,
                            UserName = "selin"
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId")
                        .IsUnique();

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(745),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(756),
                            PsychologistId = 1,
                            Url = "k-1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(760),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(760),
                            PsychologistId = 2,
                            Url = "e-1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(762),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(762),
                            PsychologistId = 3,
                            Url = "k-2.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(764),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(765),
                            PsychologistId = 4,
                            Url = "e-2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(766),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(767),
                            PsychologistId = 5,
                            Url = "k-3.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(768),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(769),
                            PsychologistId = 6,
                            Url = "e-3.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(770),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(775),
                            PsychologistId = 7,
                            Url = "k-4.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(786),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(787),
                            PsychologistId = 8,
                            Url = "e-4.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(788),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(789),
                            PsychologistId = 9,
                            Url = "k-5.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(790),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 12, 0, 15, 30, 295, DateTimeKind.Local).AddTicks(791),
                            PsychologistId = 10,
                            Url = "e-5.jpg"
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PsychologistId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Psychologist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PsychologistDescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistDescriptionId")
                        .IsUnique();

                    b.HasIndex("userId");

                    b.ToTable("Psychologist");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.PsychologistCategory", b =>
                {
                    b.Property<int>("PsychologistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PsychologistId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PsychologistCategory");

                    b.HasData(
                        new
                        {
                            PsychologistId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            PsychologistId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            PsychologistId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            PsychologistId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            PsychologistId = 2,
                            CategoryId = 5
                        },
                        new
                        {
                            PsychologistId = 2,
                            CategoryId = 6
                        },
                        new
                        {
                            PsychologistId = 3,
                            CategoryId = 7
                        },
                        new
                        {
                            PsychologistId = 3,
                            CategoryId = 8
                        },
                        new
                        {
                            PsychologistId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            PsychologistId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            PsychologistId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            PsychologistId = 4,
                            CategoryId = 4
                        },
                        new
                        {
                            PsychologistId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            PsychologistId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            PsychologistId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            PsychologistId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            PsychologistId = 6,
                            CategoryId = 5
                        },
                        new
                        {
                            PsychologistId = 6,
                            CategoryId = 6
                        },
                        new
                        {
                            PsychologistId = 7,
                            CategoryId = 7
                        },
                        new
                        {
                            PsychologistId = 7,
                            CategoryId = 8
                        },
                        new
                        {
                            PsychologistId = 7,
                            CategoryId = 5
                        },
                        new
                        {
                            PsychologistId = 8,
                            CategoryId = 6
                        },
                        new
                        {
                            PsychologistId = 8,
                            CategoryId = 7
                        },
                        new
                        {
                            PsychologistId = 9,
                            CategoryId = 8
                        },
                        new
                        {
                            PsychologistId = 9,
                            CategoryId = 5
                        },
                        new
                        {
                            PsychologistId = 9,
                            CategoryId = 4
                        },
                        new
                        {
                            PsychologistId = 10,
                            CategoryId = 6
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.PsychologistDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GraduationYear")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PsychologistDescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Sosyal Terapist, Bağımlılık Terapisti, Psikodrama Yöneticisi, Organizasyon Geliştirici İzmir Üniversitesi bölümünü tamamlayıp, ardından Almanya’da Sağlık Managment Yüksek Lisans Master egitimini  Magdeburg-Stendal Yüksekokulunda tamamlamıştır. Almanya’da psikososyal alanda 1982 yılından itibaren mesleki calışmasına paralel, 2013 tarihine kadar Sosyalterapi, Bagimlilik terapisti, Psikodrama Grup Yöneticisi, Organizasyon Geliştirici ve Choac  eğitimlerini aldı.",
                            BirthDate = new DateTime(1978, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "İzmir Üniversitesi Psikoloji",
                            Experience = "Online ve Yüz yüze Terapi",
                            GraduationYear = new DateTime(2000, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            About = "Bireysel terapi, grup terapisi, cinsel sağlık, madde bağımlılığı, anksiyete ve depresyon konularında uzmanım. Terapi sürecinde öncelikle güvenli bir ilişki kurmayı hedeflerim. İletişim becerileri, bilişsel davranışçı terapi, psikodinamik yaklaşım gibi farklı terapi yöntemleri kullanırım.",
                            BirthDate = new DateTime(1980, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Hacettepe Üniversitesi Psikoloji",
                            Experience = "Bireysel ve Grup Terapisi",
                            GraduationYear = new DateTime(2005, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            About = "İyi bir dinleyici ve gözlemciyim. Terapi sürecinde öncelikle danışanın sorunlarına odaklanarak, onun düşünce ve duygularını anlamaya çalışırım. Depresyon, anksiyete, panik atak gibi konularda terapi süreci yürütmekteyim.",
                            BirthDate = new DateTime(1985, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Boğaziçi Üniversitesi Psikoloji",
                            Experience = "Depresyon ve Anksiyete Terapisi",
                            GraduationYear = new DateTime(2007, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            About = "Çocuklar ve ailelerine yönelik terapi süreçlerinde, oyun terapisi, sanat terapisi ve aile danışmanlığı gibi yöntemleri kullanmaktayım. Her çocuğun farklı bir yapısı olduğunu ve ona göre bir terapi planı hazırlanması gerektiğini düşünmekteyim.",
                            BirthDate = new DateTime(1979, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Ankara Üniversitesi Psikoloji",
                            Experience = "Çocuk ve Aile Terapisi",
                            GraduationYear = new DateTime(2010, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            About = "Stres ve öfke yönetimi konularında uzmanım. Terapi sürecinde, danışanın stres ve öfke seviyesini düşürmek için birlikte çalışırız. Bunun için bilişsel davranışçı terapi, nefes egzersizleri, meditasyon ve benzeri yöntemler kullanmaktayım.",
                            BirthDate = new DateTime(1976, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "İstanbul Üniversitesi Psikoloji",
                            Experience = "Stres ve Öfke Yönetimi",
                            GraduationYear = new DateTime(2002, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            About = "Ankara Üniversitesi Psikoloji bölümünden mezun olan psikolog, çift terapisi ve aile terapisi konularında uzmanlaşmıştır. Terapi yöntemleri arasında Bilişsel-Davranışçı Terapi, Çözüm Odaklı Terapi ve Şema Terapi bulunmaktadır.",
                            BirthDate = new DateTime(1985, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Ankara Üniversitesi Psikoloji",
                            Experience = "Aile Terapisi, Çift Terapisi",
                            GraduationYear = new DateTime(2008, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            About = "Boğaziçi Üniversitesi Psikoloji bölümünden mezun olan psikolog, ergen terapisi ve bağımlılık terapisi konularında uzmanlaşmıştır. Terapi yöntemleri arasında Bilişsel-Davranışçı Terapi, Motivasyonel Röportaj ve EMDR bulunmaktadır.",
                            BirthDate = new DateTime(1982, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Boğaziçi Üniversitesi Psikoloji",
                            Experience = "Ergen Terapisi, Bağımlılık Terapisi",
                            GraduationYear = new DateTime(2005, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            About = "Hacettepe Üniversitesi Psikoloji bölümünden mezun olan psikolog, stres yönetimi ve depresyon terapisi konularında uzmanlaşmıştır. Terapi yöntemleri arasında Bilişsel-Davranışçı Terapi, Psikanalitik Terapi ve EFT bulunmaktadır.",
                            BirthDate = new DateTime(1989, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Hacettepe Üniversitesi Psikoloji",
                            Experience = "Stres Yönetimi, Depresyon Terapisi",
                            GraduationYear = new DateTime(2012, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            About = "İstanbul Üniversitesi Psikoloji bölümünden mezun olan psikolog, bireysel terapi, çift terapisi ve aile terapisi konularında uzmanlaşmıştır. Terapi yöntemleri arasında Bilişsel-Davranışçı Terapi, Şema Terapi ve Gestalt Terapi bulunmaktadır.",
                            BirthDate = new DateTime(1980, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "İstanbul Üniversitesi Psikoloji",
                            Experience = "Bireysel Terapi, Çift Terapisi, Aile Terapisi",
                            GraduationYear = new DateTime(2003, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            About = "Çocuklarla ve aileleriyle çalışmayı seven bir terapistim. Özellikle, çocuklarda davranış sorunları, kaygı, depresyon ve dikkat eksikliği konularında deneyimim var. Tedavide, bütünsel bir yaklaşım benimsemekteyim ve bu doğrultuda bireysel terapi, aile terapisi ve ebeveyn rehberliği gibi yöntemleri kullanmaktayım.",
                            BirthDate = new DateTime(1985, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "Hacettepe Üniversitesi Psikoloji",
                            Experience = "Çocuk ve Aile Terapisi",
                            GraduationYear = new DateTime(2008, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "90699b40-fa10-4920-9b87-03be756306e2",
                            RoleId = "2b7b70ec-d6cf-42bc-bfd8-336a35616140"
                        },
                        new
                        {
                            UserId = "022169b4-75b1-4c4c-a27e-0e6660a656b9",
                            RoleId = "2b7b70ec-d6cf-42bc-bfd8-336a35616140"
                        },
                        new
                        {
                            UserId = "f053af86-2a08-44b5-bb35-6516478773ba",
                            RoleId = "2d75e05d-f650-453c-a1fb-305396ede74f"
                        },
                        new
                        {
                            UserId = "7d97d1e4-fce7-445e-9752-91816ceb8c2a",
                            RoleId = "f69957c7-6805-4d84-aa1c-a4f7956eb8e4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Cart", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.CartItem", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultancyApp.Entity.Concrete.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Category", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.CategoryDescription", "CategoryDescription")
                        .WithOne("Category")
                        .HasForeignKey("ConsultancyApp.Entity.Concrete.Category", "CategoryDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryDescription");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Customer", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Psychologist", "Psychologist")
                        .WithMany("Customer")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultancyApp.Entity.Concrete.Identity.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychologist");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Image", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Psychologist", "Psychologist")
                        .WithOne("Image")
                        .HasForeignKey("ConsultancyApp.Entity.Concrete.Image", "PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Order", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.OrderItem", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultancyApp.Entity.Concrete.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Psychologist", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.PsychologistDescription", "PsychologistDescription")
                        .WithOne("Psychologist")
                        .HasForeignKey("ConsultancyApp.Entity.Concrete.Psychologist", "PsychologistDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultancyApp.Entity.Concrete.Identity.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PsychologistDescription");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.PsychologistCategory", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Category", "Category")
                        .WithMany("PsychologitstCategry")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultancyApp.Entity.Concrete.Psychologist", "Psychologist")
                        .WithMany("PsychologistCategory")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultancyApp.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Category", b =>
                {
                    b.Navigation("PsychologitstCategry");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.CategoryDescription", b =>
                {
                    b.Navigation("Category");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Psychologist", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Image");

                    b.Navigation("PsychologistCategory");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.PsychologistDescription", b =>
                {
                    b.Navigation("Psychologist");
                });
#pragma warning restore 612, 618
        }
    }
}
